# Generated by Django 5.2.4 on 2025-09-25 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('trainer_or_staff', models.CharField(choices=[('trainer', 'Trainer'), ('staff', 'Staff')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('blood_group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('total_fee', models.IntegerField(default=0)),
                ('due_amount', models.IntegerField(default=0)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('rejoin_date', models.DateField(blank=True, null=True)),
                ('plan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.plan')),
            ],
        ),
    ]
