# Generated by Django 5.2.4 on 2025-10-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_branch_member_branch_plan_branch_trainerstaff_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchadminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
