# Generated by Django 5.2.4 on 2025-08-20 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_leave_date_member_rejoin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
