# Generated by Django 5.2.4 on 2025-08-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_plan_member_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('trainer_or_staff', models.CharField(choices=[('trainer', 'Trainer'), ('staff', 'Staff')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('blood_group', models.CharField(max_length=5)),
            ],
        ),
    ]
